Simplify pango collapsing by using pango_aliasor package
nextstrain/forecasts-ncov pull request #39
Opened 2023-05-03 17:00 UTC by corneliusroemer

Followup of #35

I've previously written the [pango_aliasor](https://github.com/corneliusroemer/pango_aliasor) package to simplify
collapsing and aliasing of Pango lineage names

Using that package (available through pip and bioconda) removes a lot of code
No more reliance on a Nextclade tree to get aliasing info
Instead aliasing info comes from the root source, the pango-designation repo

The only downside is that we don't currently install pango_aliasor in docker-base
But there's no real reason why we shouldn't add it there
It's a small python package on the order of kB with no dependencies other than Python>3.7

2023-05-03 17:51 UTC, joverlee521 requested changes
Very cool! I totally missed that you made the `pango_aliasor` package @corneliusroemer!

> The only downside is that we don't currently install pango_aliasor in docker-base
But there's no real reason why we shouldn't add it there

The model workflows currently run on AWS Batch with the nextstrain/base image, so this change would have to wait on adding the package to docker-base. 

---

Going through the `pango_aliasor` docs, I think we can directly use the `aliasor.parent()` method instead of applying uncompress/compress. 

I believe we are uncompressing to be able to find the parent lineage with our naive `get_parent` function. Through my brief testing, it seems like `aliasor.parent()` can accept the compressed lineage and also returns the parent with the compressed name. 
```python
>>> from pango_aliasor.aliasor import Aliasor
>>> aliasor = Aliasor()
>>> lineage = "BQ.1.1.11"
>>> parent = aliasor.parent(lineage)
>>> parent
'BQ.1.1'
>>> grandparent = aliasor.parent(parent)
>>> grandparent
'BQ.1'
>>> great_grandparent = aliasor.parent(grandparent)
>>> great_grandparent
'BE.1.1.1'
```

2023-05-03 18:04 UTC, corneliusroemer commented
Thanks @joverlee521 - I think you're right! There may not be a need to uncompress at all after all. Though one needs to be careful to still create a parent of "other" when there is no parent (`aliasor.parent("XBC")` would currently yield `''`)

2023-05-03 18:38 UTC, corneliusroemer commented
@joverlee521 I'm now using `aliasor.parent`, it works indeed, and now there is even less code 👍 

Note that the collapsing logic may have a logic error in that it collapses parents before all the children to be collapsed have been collapsed. We should collapse from children inwards, only collapse a parent when all its children are either collapsed or big enough.

I can easily fix this, but it’s a bit late here, so maybe tomorrow)

2023-05-05 10:26 UTC, corneliusroemer commented
Are you happy with it now @joverlee521? I've re-requested review

2023-05-05 18:32 UTC, joverlee521 approved these changes
Thanks for jumping into this work @corneliusroemer! 

I pushed up some more tests to cover the situations you've brought up and removed the unused `extract-pango-aliasing` script. 

I've left a couple of small suggestions, but nothing blocking.

2023-05-05 18:32 UTC, joverlee521 commented on scripts/collapse-lineage-counts.py
> +                seq_counts.loc[seq_counts["variant"] == lineage, "variant"] = parent
_non-blocking_

I think this could potentially go through some extra loops even when there are no more low count lineages.
What do you think about:
```python
while len(low_count_lineages) > 0:
    max_lineage_depth = max(map(lambda x: lineage_depth(x, aliasor), low_count_lineages))
    print("Depth:", max_lineage_depth)
    print("Low count lineages:", len(low_count_lineages))
    print(low_count_lineages)
    for lineage in low_count_lineages:
        if lineage_depth(lineage, aliasor) == max_lineage_depth:
            parent = aliasor.parent(lineage) or "other"
            seq_counts.loc[seq_counts["variant"] == lineage, "variant"] = parent

    low_count_lineages = get_low_count_lineages(seq_counts, collapse_threshold)
```

2023-05-05 18:33 UTC, joverlee521 commented on scripts/collapse-lineage-counts.py
> +    low_count_lineages.discard("other")
Covering this in the new tests pushed up in https://github.com/nextstrain/forecasts-ncov/pull/39/commits/3f2dc3cf8356ba4882e6f50fcdaba438e01dad9e.

2023-05-05 20:18 UTC, trvrb commented
Thanks so much for PRs here @corneliusroemer 🌟. This is a huge improvement both in terms of code overhead (by using `pango_aliasor`) and in terms of algorithm (to work upwards from tips). I just made some simple changes in the above commit to reduce verbosity of the standard out logging. Otherwise it looks great to me.

And thank you for adding tests @joverlee521 🙏.

2023-05-05 20:19 UTC, trvrb approved these changes

2023-05-08 10:53 UTC, corneliusroemer commented on scripts/collapse-lineage-counts.py
> +                seq_counts.loc[seq_counts["variant"] == lineage, "variant"] = parent
Sure, it doesn't take long so I thought no harm in having it go through unnecessary step - happy with either

2023-05-08 10:53 UTC, corneliusroemer commented
Now just blocked by https://github.com/nextstrain/forecasts-ncov/pull/39

2023-05-17 17:07 UTC, joverlee521 commented
Waiting on the latest [nextstrain/base image to be pushed](https://github.com/nextstrain/docker-base/actions/runs/5005802577) to merge this.

2023-05-17 18:29 UTC, merged