Unify colour & display name setting for all models
nextstrain/forecasts-ncov pull request #67
Opened 2023-10-24 04:34 UTC by jameshadfield

Over time setting the clade colours & display names separately to the lineage colour definitions resulted in the two falling out of sync. This work unifies the approach so that the same script (using a unified configuration) modifies each JSON respectively.

Including the colour and display name data within the clades JSON is a big improvement as it allows simple retrospective analysis of old datasets.

2023-10-24 04:35 UTC, jameshadfield commented on workflow/snakemake_rules/models.smk
> +rule post_process_nextstrain_clades_output:
@joverlee521 could you take a look at the Snakemake changes here please? 🙏

2023-10-24 04:36 UTC, jameshadfield commented on scripts/modify-lineage-colours-and-order.py
> +        sys.exit(2)
@joverlee521 I've chosen to exit here (which will cause the model runs to fail) but there are other options if you think it's better for them to succeed even if we forgot to update the colour definitions?

2023-10-24 04:36 UTC, jameshadfield commented on viz/src/config.js
> -  ["22B",   "#999999"],
22B, 22D and 22E were not copied over to the new configuration as they were not present in the latest model runs.

2023-10-24 18:12 UTC, trvrb commented on workflow/snakemake_rules/models.smk
> +rule post_process_pango_lineages_output:
Rule `post_process_nextstrain_clades_output` currently applies to `variant_classification=pango_lineages` with `--lineages-in {input}`, while rule `post_process_pango_lineages_output` currently applies to `variant_classification=nextstrain_clades`. It looks like there's a label swap here.

2023-10-24 18:23 UTC, trvrb requested changes
I very much appreciate the centralization and moving colors into the JSON. Can I request one change however... the rest of workflow is quite good at putting everything you need to modify into `config/config.yaml`. The `CLADES` entry in `modify-lineage-colours-and-order.py` is now the exception and requires modifying the script itself. Can you move the `CLADES` entry into `config/config.yaml`? Or should this wait on unifying the hex values and the `cmap` entries? I think can be out of scope for this PR, but would be very useful to have a direct hex map here. As it stands if we add an additional clade you have to rejigger the start and stop values across different cmaps and have to do visual inspection to line up hex values with cmaps. My suggestion would be to drop cmaps  and instead pad directly from hex values. This will keep things more easily in sync.

2023-10-24 21:25 UTC, trvrb commented
Another observation (that I don't know where to thread really)... if I take the resulting file `2023-10-24_results.json` and drag-n-drop to https://nextstrain.github.io/forecasts-viz/ the resulting display is the generic color ramp rather than the hex values encoded in the JSON.

2023-10-24 23:31 UTC, jameshadfield commented
I've updated this PR to generate colour ranges from the provided clade colour (see commentary in the code of that function - I don't think the colours are _better_ than using cmaps, but they are certainly much easier to maintain!) and also shifted the clade definitions into the config.

![image](https://github.com/nextstrain/forecasts-ncov/assets/8350992/1b552afb-59fd-4846-9c43-4c018f58fbb2)

2023-10-24 23:40 UTC, jameshadfield commented on workflow/snakemake_rules/models.smk
> +rule post_process_pango_lineages_output:
Thanks! Fixed up

2023-10-25 19:28 UTC, joverlee521 commented on workflow/snakemake_rules/models.smk
> +rule post_process_nextstrain_clades_output:
I'd recommend combining the two rules since both rules are using `modify-lineage-colours-and-order.py`. 

Instead of using the `--lineages-in/--lineages-out` and `--clades-in/--clades-out` options as flags, maybe add a new `--variant-classification` option with the previous `input/output` options. I'm imagining this would then look something like: 

```python
shell:
      """
      python ./scripts/modify-lineage-colours-and-order.py \
            --input {input} \
            --output {output} \
            --config {params:q} \
            --variant-classification {wildcards.variant_classification} 2>&1 | tee {log}
      """
```

Then within `modify-lineage-colours-and-order.py` there would be an if/elif/else block based on the provided variant classification:

```python
if args.variant_classification == 'nextstrain_clade':
      ...
elif args.variant_classification == 'pango_lineage':
      ...
else:
      shutil.copy(args.input, args.output)
```

2023-10-25 20:01 UTC, joverlee521 commented on scripts/modify-lineage-colours-and-order.py
> +        sys.exit(2)
I think it's reasonable to have this failure to alert us to update the color definitions. 

For clearer stack trace, I recommend changing this to an assert statement:
```python
assert len(missing) == 0, f"Missing definitions for the following clades: {', '.join(missing)}"
```

2023-10-26 01:21 UTC, jameshadfield commented on workflow/snakemake_rules/models.smk
> +rule post_process_nextstrain_clades_output:
Great suggestion! Changed to use this approach

2023-10-26 01:26 UTC, jameshadfield commented on scripts/modify-lineage-colours-and-order.py
> +        sys.exit(2)
Sure! Changed to use `assert`

(I don't tend to use assert statements in python because I'm never sure which environments set `PYTHONOPTIMIZE`, and I tend to hide stack traces when the error message is instructive, but they're more guidelines to me than rules.)

2023-10-26 17:02 UTC, joverlee521 commented on scripts/modify-lineage-colours-and-order.py
> +        sys.exit(2)
Oh, TIL about `PYTHONOPTIMIZE`! I guess that would argue for raising an Exception, but I think fine to leave as is.

2023-10-26 17:49 UTC, tsibley commented on scripts/modify-lineage-colours-and-order.py
> +        sys.exit(2)
Conventions will vary across communities within Python, but I wouldn't assume any Python software was safe under `PYTHONOPTIMIZE` without it being documented to be so.

You have to have a lot of asserts (or `if __debug__:` blocks) or very slow ones for their removal to make an actual difference in performance. I think about `PYTHONOPTIMIZE` (or `-O`, optimization level 1) as mostly about optimizing for bytecode size on disk. And this focus explains why `-OO` (optimization level 2) goes on to also remove docstrings in addition to asserts/`if __debug__`. It's about compact bytecode, not runtime performance per se, and compact bytecode is not esp. compelling given today's quantities of disk and memory.

So I wouldn't particularly let the existence of optimization stop us from using asserts, as it doesn't stop us from using docstrings at runtime either. If we really want to be defensive, we can do something like what I did in ID3C years ago: [assert that asserts are enabled](https://github.com/seattleflu/id3c/commit/ba1aaa20ffeaf9ace08fbeb8eee01918915607bc).

2023-10-30 19:43 UTC, jameshadfield commented
I'm going to merge this now - any colour fixes (etc) can be easily applied by subsequent PRs if needed.

2023-10-30 19:43 UTC, merged

2023-11-06 21:13 UTC, trvrb commented
Thanks so much for the changes here James (and sorry that I forget to follow up). I really appreciate this. It should make things much more maintainable going forward.